### ISSUE TITLE
Need command line option to set file naming based on OS

### ISSUE THREAD

**Issue by ProtoSD** [dbr/tvnamer#122]
I use TVnamer in a script on my NAS to name files that I view from Windows. I'm getting file names with invalid characters (example title with time 12:53). The colon causes the file to appear like H46UDG~1.mp4. TVnamer thinks the file name is valid since its running on Linux.

**Comment by ProtoSD** [comment]
Please disregard, I discovered the option in the configuration file! My mistake. Thanks for the great app!

**Comment by shalak** [comment]
Since I landed here when I had the same issue, allow me to post a fix:

In `~/.config/tvnamer/tvnamer.json` enter:
```json
{
    "windows_safe_filenames": true,
    "output_filename_replacements": [
        {"is_regex": false,
        "match": ":",
        "replacement": " -"}
    ]
}
```

The `windows_safe_filenames` will take care of all windows-illegal characters and replace them with `_`.

The `output_filename_replacements` will treat the `:` differently, replacing it with ` -` instead (thanks to this, titles like `Chapter 1: Title`, will be changed to `Chapter 1 - Title`
