### ISSUE TITLE
tvdb api now needs key

### ISSUE THREAD

**Issue by georghuber** [dbr/tvnamer#194]
Hi, I use tvnamer 2.5 under FreeBSD. Until recently it worked perfectly until TheTVDB changed the access and now requires a (paid) key. So I paid a 1 year subscription and received a legacy API key. I edited the config_defaults.py file according to the sample config file here on github and added the line

`# Custom API key from www.thetvdb.com - if None, uses tvnamer's default key
    'tvdb_api_key': '5c59********f46a4db97196e61f',
`
But I do get the followien error:

`ValueError: apikey argument is now required - an API key can be easily registered at https://thetvdb.com/api-information`

If I do not use the ' ' I get another error:

` File "/usr/local/lib/python3.7/site-packages/tvnamer/config_defaults.py", line 8
    'tvdb_api_key': 5c59d824********6a4db97196e61f,
`

I suspect it is something with the Syntax, as I really have no idea what I am doing in Python (sorry).

Do you have any clue, what I do wrong?

Many thanks again (I am a returning customer).

Georg

I attach the config.defaults.py file
[config_defaults.zip](https://github.com/dbr/tvnamer/files/5359696/config_defaults.zip)

**Comment by dbr** [comment]
Huh, that is the first I've heard of TheTVDB access becoming paid only 😕 Seems to be remarkably little announcement of this, not even their blog mentions it currently.. but anyway:

The config in the first example is most likely correct, I think the issue is the version of tvnamer packaged for FreeBSD is outdated (2.5) while the tvdb_api module has been updated to 3.0.1. These two versions are not compatible (tvnamer 3.0.1 requires tvdb_api 3.0.2)

To use your API key, you'd need to install the latest 3.x version of tvnamer. Installing the older tvdb_api would use the old bundled key which, I assume, will stop working at some point (if it's not already)?

**Comment by georghuber** [comment]
Hi the maintainer just updated the port, many thanks for your input, so I could post it on FreeBSD bugzilla.

it seems that the tvnamer key ('tvdb_api_key': None,) still works btw, but now that I have a custom key, I'll be using this one :-) (works!)

One last question: when I verbose, I get this warning:

`WARNING: you have a config at deprecated ~/.tvnamer.json location.
This must be moved to new location: ~/.config/tvnamer/tvnamer.json`

I have no "~/.config/tvnamer" directory. Do I need to create one or can I just stay where I am (~/)?

Best, Georg

**Comment by dbr** [comment]
> it seems that the tvnamer key ('tvdb_api_key': None,) still works btw, but now that I have a custom key, I'll be using this one :-) (works!)

Excellent, thanks for getting the port updated! Yep there is a default key for tvnamer, with the option to override to a custom one

Regarding the config location, `~/.config/tvnamer/tvnamer.json` is the new preferred location as per #166 - so I'd recommend moving your config to there (in some future version the old location will stop working)
